### ISSUE TITLE
Linux x64, returning -1 from app to python is wrong

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#286] opened 2021-02-16 08:45 UTC
CudaText (Py4Lazarus) suffers from it- return of -1 (PyInt_FromLong AFAIR) in APIs may give MaxDWORD (big number) for python.
I need to make repro for you.
or it is known problem?

**Comment by pyscripter** [comment] 2021-02-16 10:51
This probably relates to #197.  Have you seen the latest discussion on this?

**Comment by Alexey-T** [comment] 2021-02-16 11:04
Made a demo,
https://github.com/alexey-T/python-for-lazarus , demo "python console".
after you run it, enter in console
```
import demo
=demo.n1()
```

it must show -100000 but shows BIG positive int.

**Comment by pyscripter** [comment] 2021-02-16 11:23
Can you try this fix:

```pascal
  {$ifdef mswindows} 
    Long = integer
  {$else} 
    Long= NativeInt
  {$endif}

    PyLong_AsLong:function (ob:PPyObject):Long; cdecl;
    PyLong_FromLong:function (l:Long):PPyObject; cdecl;
```

**Comment by Alexey-T** [comment] 2021-02-16 11:32
patch linkied.
now it's OK.
![Screenshot from 2021-02-16 14-27-09](https://user-images.githubusercontent.com/4154978/108057471-bbd05d00-7063-11eb-9c12-2fa44ea8959c.png)

**Comment by pyscripter** [comment] 2021-02-16 11:48
Duplicate of #197

**Comment by pyscripter** [comment] 2021-02-16 11:49
Of course all other LongInts need to be changed as well.

**Comment by Alexey-T** [comment] 2021-02-16 11:52
do you mean all 'integer' from this 

![Screenshot from 2021-02-16 14-51-40](https://user-images.githubusercontent.com/4154978/108059425-8a0cc580-7066-11eb-8596-845ba5f9699e.png)

and others?
Can you make replace in your repo, so I will sync?

**Comment by Alexey-T** [comment] 2021-02-16 11:59
(let's use changed name, not 'Long', because 'Long' will appear for all users of unit)

**Comment by pyscripter** [comment] 2021-02-16 15:31
Done.

**Closed by pyscripter** 2021-02-16 15:31 UTC
Labels: duplicate
