### ISSUE TITLE
FPC/Lazarus Demos do not compile

### ISSUE THREAD

**Issue by neurolabusc** [pyscripter/python4delphi#235] opened 2020-12-03 12:26 UTC
I was unable to get any of the demo projects in the FPC folder to compile. Minor changes allowed them to compile, but they always reported an error on executation 'Could not open Dll "libpython3.9.dylib"' even when the DllName and DllPath were set correctly (or even to a python other than 3.9).

  Demo1
   Unit1.pas:rename "PythonGUIInputOutput" to "lcl.PythonGUIInputOutput"
   
  Demo6 
   Unit1: Does not include file "Definition.inc", "Windows" not in UNIX, rename "PythonGUIInputOutput" to "lcl.PythonGUIInputOutput"
   Project1.lpr: IFDEF uses identical files for Windows and Linux, fails on MacOS

**Comment by pyscripter** [comment] 2020-12-03 14:19
Duplicate of #233

**Closed** 2020-12-03 14:20 UTC
Labels: duplicate
