### ISSUE TITLE
Access Violation Error Installing the any "dcl" package of the project.

### ISSUE THREAD

**Issue by juanccilleruelo** [pyscripter/python4delphi#396] opened 2022-12-26 08:55 UTC
RAD Studio 11 (28.0.45591.0253) Professional with Mobile. 
I've opened the P4DComponentSuite in the Package/Delphi directory. 
I've built all the projects.
When I try to install dclPython280.bpl, dclPythonVcl280.bpl, and dclPythonFmx280.bpl I get an Access Violation error. In the three cases.

Next is the complete message of dclPhytonFmx280.bpl:
RegistrationProcedure, Fmx@Pythonreg.Register in package _C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl\dclPythonFmx280.bpl raised exception class EAccessViolation: Access Violation at address 50157577 in module 'rtl280.bpl'. Read of address 00000008._

I still don't have installed Python on my computer. 

I want to develop an application W64. Because of this, I've compiled all the packages in both, W32 and W64 bits. But when I try to install the components I assure that I try to install the W32 bits version, of course. (The IDE is W32 bits).

**Comment by pyscripter** [comment] 2022-12-26 09:46
Are you using the latest version from this repo?

**Comment by juanccilleruelo** [comment] 2022-12-26 13:06
> 

Yes. I cloned the repository with the SourceTree application. 
And the Windows Version is 11 too.

**Comment by pyscripter** [comment] 2022-12-26 17:41
Tried again just now.   Same configuration as yours (Windows 11, Delphi 11.2).  Installed without issues.

- Could it be a conflict with previously installed versions?
- Did you check the Delphi library path to make sure that the correct source directories are included?

You do not need to compile 64bit packages if you are not using run-time packages.
One thing you can try is to use the Multi-Installer in the Install subdirectory.   Read carefully the [instructions](https://github.com/pyscripter/python4delphi/blob/master/Install/README.md) beforehand.

**Comment by juanccilleruelo** [comment] 2022-12-26 19:28
> Tried again just now. Same configuration as yours (Windows 11, Delphi 11.2). Installed without issues.

My Delphi is 11.1
 
> * Could it be a conflict with previously installed versions?
    No. It's my first trial of this product.

> * Did you check the Delphi library path to make sure that the correct source directories are included?
    Checked!

> You do not need to compile 64-bit packages if you are not using run-time packages. 
   I thought that for the development of a 64-bit application I need 64-bit "bpls" and 64-bit Python.

**Comment by juanccilleruelo** [comment] 2022-12-29 18:13
I've installed a new virtual machine, Delphi 11.2, with the Patch. 
After, I installed Python4Delphi, and it compiles well.
This issue may be related to Delphi 11.1. 
It is optional to dedicate time to correct it.

**Comment by pyscripter** [comment] 2022-12-29 18:17
Thanks for letting me know.   I think the issue is due to conflict with previously installed P4D versions.  I will close the issue since, even if that is not the case, I would expect users of 10.1 to move to 10.2 eventually.

**Closed by pyscripter** 2022-12-29 18:17 UTC
